merger_tests:
  stage: test
  image: python:3.11-alpine
  script:
    - cd merger/src
    - pip3 install -r requirements.txt
    - python3 merger_tests.py

schema_tests:
  stage: test
  image: debian:latest
  before_script:
    - apt update
    - apt install unzip curl python3-minimal make -y
    - "curl -fsSL https://raw.githubusercontent.com/sourcemeta/jsonschema/main/install -H 'Cache-Control: no-cache, no-store, must-revalidate' | /bin/sh"
  script:
    - make test_schema
