# Use a Node.js image as base
FROM node:22-alpine

ENV MONGODB_URI="mongodb://mongodb:27017/gym"

WORKDIR /app

COPY schemas ./schemas

WORKDIR /app/control-panel

# Copy necessary files from host to container
COPY control-panel/backend ./backend
COPY control-panel/models ./models
COPY control-panel/*.json .

# Install project dependencies
RUN npm ci

WORKDIR /app/control-panel/models
RUN ../node_modules/typescript/bin/tsc
WORKDIR /app/control-panel/backend
RUN ../node_modules/typescript/bin/tsc

# Expose the port that the Express server is listening on
EXPOSE 3000

# Start the application when the container is started
CMD ["node", "app.js"]
LABEL "traefik.http.routers.backend.rule"="PathPrefix(`/api`)"
