name: Merger tests
on:
  push:
    branches: [master]
jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: python:3.11-alpine
    steps:
      - uses: actions/checkout@v3
      - name: Run tests
        run: cd merger/src && pip3 install -r requirements.txt && python3 merger_tests.py
